services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    env_file:
      - ../stack.env
    ports:
      - "${APP_PORT}:80"
    restart: unless-stopped
